
import java.awt.event.KeyEvent;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import java.sql.*;
import javax.swing.table.DefaultTableModel;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author huesi
 */
public class Principal extends javax.swing.JFrame {

    /**
     * Creates new form Principal
     */
    DefaultTableModel dtm;
    int contadorProducto;
    int total;
    int iva;
    int subtotal;
    
    public Principal() {
        initComponents();
        dtm = (DefaultTableModel) jbtDatos.getModel();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jfPagina1 = new javax.swing.JFrame();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jlbVendedor = new javax.swing.JLabel();
        jtfCodigo = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jbtDatos = new javax.swing.JTable();
        jlbProductos = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jlbTotal = new javax.swing.JLabel();
        jlbSubtotal = new javax.swing.JLabel();
        jlbIva = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jfInforme1 = new javax.swing.JFrame();
        jPanel3 = new javax.swing.JPanel();
        jlbUsuarioVentas = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jfInforme2 = new javax.swing.JFrame();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jtfUsuario = new javax.swing.JTextField();
        jpfClave = new javax.swing.JPasswordField();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();

        jPanel2.setLayout(null);

        jLabel4.setText("Mayorista PGY");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(0, 0, 90, 20);
        jPanel2.add(jlbVendedor);
        jlbVendedor.setBounds(470, 30, 110, 30);

        jtfCodigo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jtfCodigoActionPerformed(evt);
            }
        });
        jtfCodigo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jtfCodigoKeyReleased(evt);
            }
        });
        jPanel2.add(jtfCodigo);
        jtfCodigo.setBounds(120, 60, 150, 30);

        jLabel6.setText("Codigo:");
        jPanel2.add(jLabel6);
        jLabel6.setBounds(40, 60, 70, 30);

        jLabel7.setText("Usuario:");
        jPanel2.add(jLabel7);
        jLabel7.setBounds(420, 30, 50, 30);

        jButton2.setText("Informes");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton2);
        jButton2.setBounds(420, 60, 150, 32);

        jbtDatos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Codigo", "Producto", "Precio"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jbtDatos);

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(30, 100, 560, 170);

        jlbProductos.setFont(new java.awt.Font("Dialog", 1, 36)); // NOI18N
        jlbProductos.setText("0");
        jPanel2.add(jlbProductos);
        jlbProductos.setBounds(40, 320, 50, 60);

        jLabel9.setText("Total:");
        jPanel2.add(jLabel9);
        jLabel9.setBounds(430, 340, 60, 20);

        jLabel10.setText("Productos");
        jPanel2.add(jLabel10);
        jLabel10.setBounds(30, 300, 80, 20);

        jLabel11.setText("Subtotal:");
        jPanel2.add(jLabel11);
        jLabel11.setBounds(430, 300, 60, 20);

        jLabel12.setText("IVA:");
        jPanel2.add(jLabel12);
        jLabel12.setBounds(430, 320, 60, 20);
        jPanel2.add(jlbTotal);
        jlbTotal.setBounds(500, 340, 70, 20);
        jPanel2.add(jlbSubtotal);
        jlbSubtotal.setBounds(500, 300, 70, 20);
        jPanel2.add(jlbIva);
        jlbIva.setBounds(500, 320, 70, 20);

        jButton3.setText("Finalizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton3);
        jButton3.setBounds(320, 390, 120, 50);

        jButton4.setText("Cancelar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton4);
        jButton4.setBounds(180, 390, 120, 50);

        jButton5.setText("Salir ");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel2.add(jButton5);
        jButton5.setBounds(540, 440, 70, 32);

        javax.swing.GroupLayout jfPagina1Layout = new javax.swing.GroupLayout(jfPagina1.getContentPane());
        jfPagina1.getContentPane().setLayout(jfPagina1Layout);
        jfPagina1Layout.setHorizontalGroup(
            jfPagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 618, Short.MAX_VALUE)
        );
        jfPagina1Layout.setVerticalGroup(
            jfPagina1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, 474, Short.MAX_VALUE)
        );

        jPanel3.setLayout(null);
        jPanel3.add(jlbUsuarioVentas);
        jlbUsuarioVentas.setBounds(460, 40, 80, 20);

        jLabel13.setText("Informe de ventas");
        jPanel3.add(jLabel13);
        jLabel13.setBounds(40, 30, 140, 40);

        jLabel14.setText("Usuario:");
        jPanel3.add(jLabel14);
        jLabel14.setBounds(400, 40, 50, 20);

        javax.swing.GroupLayout jfInforme1Layout = new javax.swing.GroupLayout(jfInforme1.getContentPane());
        jfInforme1.getContentPane().setLayout(jfInforme1Layout);
        jfInforme1Layout.setHorizontalGroup(
            jfInforme1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 571, Short.MAX_VALUE)
        );
        jfInforme1Layout.setVerticalGroup(
            jfInforme1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, 472, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jfInforme2Layout = new javax.swing.GroupLayout(jfInforme2.getContentPane());
        jfInforme2.getContentPane().setLayout(jfInforme2Layout);
        jfInforme2Layout.setHorizontalGroup(
            jfInforme2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        jfInforme2Layout.setVerticalGroup(
            jfInforme2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setText("Clave");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(230, 200, 50, 30);

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setText("Usuario");
        jPanel1.add(jLabel2);
        jLabel2.setBounds(220, 120, 60, 30);
        jPanel1.add(jtfUsuario);
        jtfUsuario.setBounds(170, 150, 170, 40);

        jpfClave.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                jpfClaveKeyReleased(evt);
            }
        });
        jPanel1.add(jpfClave);
        jpfClave.setBounds(170, 230, 170, 40);

        jButton1.setText("Iniciar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(250, 290, 90, 40);

        jLabel3.setFont(new java.awt.Font("Dialog", 2, 14)); // NOI18N
        jLabel3.setText("Iniciar sesion");
        jPanel1.add(jLabel3);
        jLabel3.setBounds(0, 0, 90, 20);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 450, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jtfCodigoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jtfCodigoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jtfCodigoActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        conectarUsuario(jtfUsuario.getText(), jpfClave.getText());
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jtfCodigoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jtfCodigoKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) { 
         try ( Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/Mercado", "root", "")) {
            String sql = "select * from producto where codigo = ?";
            try ( PreparedStatement ps = con.prepareStatement(sql)) {
                ps.setString(1, jtfCodigo.getText());
                try ( ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                        dtm.addRow(new Object[]{
                            rs.getString("codigo"),
                            rs.getString("nombre"),
                            rs.getInt("precio")  
                            
                        });
                        jtfCodigo.setText("");
                        contadorProducto += 1;
                        total += Integer.parseInt(rs.getString("precio"));
                        subtotal += Integer.parseInt(rs.getString("precio")) * 0.81;
                        iva += Integer.parseInt(rs.getString("precio")) * 0.18;
                        jlbProductos.setText("" + contadorProducto);
                        jlbSubtotal.setText("$" + subtotal);
                        jlbIva.setText("$" + iva);
                        jlbTotal.setText("$" + total);
                    } else {
                        JOptionPane.showMessageDialog(this, "Producto no encontrado!.");
                        jtfCodigo.setText("");
                    }
                }
            }
            } catch (Exception e) {
                error("Error producido: " + e);
            }
        }
    }//GEN-LAST:event_jtfCodigoKeyReleased

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        setVisible(false);
        jfPagina1.setVisible(false);
        jfInforme1.pack();
        jfInforme1.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jpfClaveKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_jpfClaveKeyReleased
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            conectarUsuario(jtfUsuario.getText(), jpfClave.getText());
            jtfUsuario.setText("");
            jpfClave.setText("");
        }
    }//GEN-LAST:event_jpfClaveKeyReleased

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        setVisible(true);
        jfPagina1.pack();
        jfPagina1.setVisible(false);
        jtfUsuario.requestFocus();
        limpiarTodo();
    }//GEN-LAST:event_jButton5ActionPerformed

    public void limpiarTodo(){
        jlbProductos.setText("");
        jlbIva.setText("");
        jlbSubtotal.setText("");
        jlbTotal.setText("");
        dtm.setRowCount(0);
        jtfCodigo.requestFocus();
    }
    
    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        limpiarTodo();
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        try ( Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/Mercado", "root", "")) {
            String sql = "insert into venta values(0, now(), ?, ?, ?, ?)";
            try ( PreparedStatement ps = con.prepareStatement(sql)) {
                ps.setInt(1, Integer.parseInt(jlbProductos.getText()));
                ps.setInt(2, total);
                ps.setDouble(3, iva);
                ps.setString(4, jtfUsuario.getText());
                ps.executeUpdate();
                limpiarTodo();
            }     
        }catch (Exception e) {
            error("Error producido: " + e);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    public void buscarProducto(){
        
    }
    
    public void conectarUsuario(String usuario, String clave){
        try ( Connection con = DriverManager.getConnection(
            "jdbc:mysql://localhost:3306/Mercado", "root", "")) {
            String sql = "select * from usuario where usuario = ? and clave = ?";
            try ( PreparedStatement ps = con.prepareStatement(sql)) {
                ps.setString(1,usuario);
                ps.setString(2, clave);
                try ( ResultSet rs = ps.executeQuery()) {
                    if (rs.next()) {
                          setVisible(false);
                          jfPagina1.pack();
                          jfPagina1.setVisible(true);
                          jtfUsuario.setText("");
                          jpfClave.setText("");
                          jlbVendedor.setText(jtfUsuario.getText());
                    } else {
                        JOptionPane.showMessageDialog(this, "Error, usuario incorrecto!.");
                    }
                }
            }
        } catch (Exception e) {
            error("Error producido: " + e);
        }
    }
    
    public void error(String mensaje) {
        JOptionPane.showMessageDialog(this, mensaje, "Error", JOptionPane.ERROR_MESSAGE);
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jbtDatos;
    private javax.swing.JFrame jfInforme1;
    private javax.swing.JFrame jfInforme2;
    private javax.swing.JFrame jfPagina1;
    private javax.swing.JLabel jlbIva;
    private javax.swing.JLabel jlbProductos;
    private javax.swing.JLabel jlbSubtotal;
    private javax.swing.JLabel jlbTotal;
    private javax.swing.JLabel jlbUsuarioVentas;
    private javax.swing.JLabel jlbVendedor;
    private javax.swing.JPasswordField jpfClave;
    private javax.swing.JTextField jtfCodigo;
    private javax.swing.JTextField jtfUsuario;
    // End of variables declaration//GEN-END:variables
}
